### ISSUE TITLE
DeprecationWarning: The `punycode` module is deprecated

### ISSUE THREAD

**Issue by sebagr** [mistval/node-fetch-cache#47] opened 2024-05-17 14:52 UTC
(node:84849) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.

This is caused by node-fetch 2.*

Solution is to upgrade to latest node-fetch^3

**Comment by mistval** [comment] 2024-05-18 17:24
Hi, could you provide detailed steps to reproduce that warning?

**Comment by sebagr** [comment] 2024-05-18 17:29
Sorry, forgot to mention this happens as of Node 21, where punycode is deprecated.

**Comment by mistval** [comment] 2024-05-18 17:37
Ah thanks, I can reproduce. I'll see if I can update to node-fetch v3 (might be a little hairy since it's ESM and might have different internals from the ones that node-fetch-cache relies on in v2).

**Comment by mistval** [comment] 2024-08-17 15:30
This is fixed with the newly published v5 which upgrades to node-fetch v3.

**Closed as completed by mistval** 2024-08-17 15:30 UTC
Labels: enhancement, dependencies
